# _config.yml

# required, replace with your own information -----
title: generousjj
author: generousjj
description: > 
  he/him • i play games and code sometimes.
  python programmer, graphic designer
baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
#---------------------------------------------------

exclude:
  - vendor/
  - vendor/bundle/
  - tmp/
  - ruby/2.7.0/
  - vendor
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - gems
  - _posts/0000-00-00-welcome-to-jekyll.markdown.erb
  - ruby
  - vendors
  - vercel/path0/vendor
  - vercel
  - path0/vendor
