# _config.yml

# required, replace with your own information -----
title: generousjj
author: generousjj
description: > 
  he/him • i play games and code sometimes.
  python programmer, graphic designer
baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
#---------------------------------------------------

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor
  - vendors
  - vercel/path0/vendor
  - path0/vendor
